name: 'main'
on:
  - push
jobs:
  main:
    name: 'main'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
      - name: 'main'
        uses: ./
        with:
          myin1: "foo"
